---
title: "Conference"
author: "Richard G. Gardiner"
date: "4/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(tidytext)
library(wordcloud)
library(readxl)
library(widyr)
library(igraph)
library(ggraph)
library(stringr)
```

Steps necessary:

```{r}
conference_raw <- read_excel("Conference Talks.xlsx") %>%
  mutate(year = 2019,
         conference = "April")

numbers <- seq(1:100)


# unigram
conference <- conference_raw %>%
  unnest_tokens(word, Text) %>%
  anti_join(stop_words, by = "word") %>%
  filter(!(word %in% c(numbers)))



conference %>%
  count(word, sort = TRUE) %>%
  top_n(10) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  coord_flip() +
  theme_light() +
  labs(x = "Number of Occurances", y = "Word",
       title = "Which Words Were Mentioned Most?")

conference %>%
  count(word) %>%
  with(wordcloud(word, n, max.words = 100))
```

## Bigram

Counts: nothing interesting
```{r}
# bigram
conference_bigram <- conference_raw %>%
  unnest_tokens(bigram, Text, token = "ngrams", n = 2) %>%
  separate(bigram, c("word1", "word2"), sep = " ") %>%
  filter(!(word1 %in% stop_words$word),
         !(word2 %in% stop_words$word),
         !(word1 %in% numbers),
         !(word2 %in% numbers)) %>%
  unite(bigram, word1, word2, sep = " ")

conference_bigram %>%
  group_by(Session) %>%
  count(bigram, sort = TRUE) %>%
  top_n(10, bigram) %>%
  ungroup() %>%
  mutate(bigram = fct_reorder(bigram, n)) %>%
  ggplot(aes(bigram, n, fill = Session)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  facet_wrap(~Session, scale = "free_y")
```

Correlation

```{r}
word_cors <- conference %>%
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(word, Talk, sort = TRUE) %>%
  filter(correlation != 1)

word_cors
```

```{r}
data$carb <- factor(data$carb, levels = data$carb[order(-data$mpg)])


word_cors %>%
  filter(item1 %in% c("church", "love", "gospel", "temple")) %>%
  group_by(item1) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(item2 = reorder(item2, desc(correlation))) %>% 
  ggplot(aes(item2, correlation,  fill = item1)) +
  geom_col(show.legend = FALSE) +
  facet_wrap( ~ item1, scales = "free_y") +
  coord_flip() +
  theme_light() +
  labs(x = "Correlation", y = "Word", 
       title = "Correlation between Words")

# ggsave("Correlation between words.jpeg")
```

```{r}
set.seed(2016)

word_cors %>%
  filter(correlation > .50) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), show.legend = FALSE) +
  geom_node_point(color = "lightblue", size = 5) +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void()

# ggsave("network graph.jpeg")
```


```{r}
# creating necessary functions
count_bigrams <- function(dataset) {
  dataset %>%
    unnest_tokens(bigram, Text, token = "ngrams", n = 2) %>%
    separate(bigram, c("word1", "word2"), sep = " ") %>%
    filter(!word1 %in% stop_words$word,
           !word2 %in% stop_words$word) %>%
    count(word1, word2, sort = TRUE)
}

visualize_bigrams <- function(bigrams) {
  set.seed(2016)
  a <- grid::arrow(type = "closed", length = unit(.15, "inches"))
  
  bigrams %>%
    graph_from_data_frame() %>%
    ggraph(layout = "fr") +
    geom_edge_link(aes(edge_alpha = n), show.legend = FALSE, arrow = a) +
    geom_node_point(color = "lightblue", size = 5) +
    geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
    theme_void()
}

conference_raw %>%
  count_bigrams() %>%
  filter(n > 5,
  !str_detect(word1, "\\d"),
  !str_detect(word2, "\\d")) %>%
  visualize_bigrams()
```









5. tf_idf
    - get unique words for people
6. topic modeling
    - Use this informed maybe by word clouds
    
    
    